# Generated by Django 4.1 on 2022-11-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_reaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reaction',
            new_name='ReactionType',
        ),
    ]
