# Generated by Django 4.1 on 2022-09-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
