# Generated by Django 4.1 on 2022-09-18 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watcher',
            field=models.ManyToManyField(blank=True, related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
