# Generated by Django 4.1 on 2022-09-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_watcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='watcher',
        ),
    ]
