# Generated by Django 4.1 on 2022-09-25 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_active_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2005, 4, 2, 21, 37)),
            preserve_default=False,
        ),
    ]
